name: Craftabouts Custom Blocks
main: us.hinchy.CraftaboutsCustomBlocks.CraftaboutsCustomBlocks
version: 4
description: Spout custom blocks for the Craftabouts Minecraft server.
author: Zach Hinchy
website: http://mine.wearethelayabouts.com/
depend: [Spout]